version: '3.7'

networks:
    sqli2022_workshop_net:

services:
    d9_server:
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        container_name: '${APP_NAME}-server'
        expose:
            - "9000"
            - "9003"
        ports:
            - '80:80'
        working_dir: /var/www/html
        # Enable this to prioritize it
        #environment:
        #    - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5'
        volumes:
            - ./codebase:/var/www/html
            - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
            - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
            - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - db_server
        networks:
            - sqli2022_workshop_net

    db_server:
        image: mariadb:10.5.9
        container_name: '${APP_NAME}-db'
        #restart: always
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASS}'
            MYSQL_DATABASE: '${MYSQL_DB}'
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        networks:
            - sqli2022_workshop_net

    db_admin:
        image: phpmyadmin/phpmyadmin:5
        container_name: '${APP_NAME}-db-admin'
        ports:
            - '${APP_DB_ADMIN_PORT}:80'
        environment:
            PMA_HOST: db_server
        depends_on:
            - db_server
        volumes:
            - db_admin_data:/var/www/html
        networks:
            - sqli2022_workshop_net

    mailcatcher:
        container_name: '${APP_NAME}-mailer'
        networks:
            - sqli2022_workshop_net
        image: yappabe/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080

volumes:
    db_data:
    db_admin_data:
