
<?php

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */

/*function feedback_form_form_alter(&$form, &$form_state, $form_id)
{
    if ($form_id == 'node-exercise-form' ) {
      $form['revision_information']['#access'] = false;
      unset($form['field_content']['#description']);
    }
}*/
