features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://Logo.png'
favicon:
  use_default: 0
  path: 'public://favicon.png'
  mimetype: image/png
all_icons_show: 1
facebook_url: 'https://www.facebook.com/idewdot'
twitter_url: 'https://twitter.com/dewdots'
instagram_url: 'https://www.instagram.com/google'
linkedin_url: 'https://in.linkedin.com/company/google'
youtube_url: 'https://www.youtube.com/user/Google'
vimeo_url: 'https://vimeo.com/'
telegram_url: 'https://telegram.org/'
whatsapp_url: 'https://web.whatsapp.com/'
github_url: 'https://github.com/'
vk_url: ''
slider_show: 0
slider_image: {  }
slider_code: ''
front_sidebar: 0
font_icon_fontawesome: 0
font_icon_fontawesome5: 0
font_icon_material: 0
comment_user_pic: 1
node_author_pic: 0
node_tags: 0
scrolltotop_on: 1
copyright_text: 1
styling: 0
styling_code: ''
