login:
  authenticated:
    redirect_url: ''
    weight: '-10'
  content_editor:
    redirect_url: ''
    weight: '-10'
  administrator:
    redirect_url: ''
    weight: '-10'
  formateur:
    redirect_url: ''
    weight: '-10'
  stagiaire:
    redirect_url: ''
    weight: '-10'
logout:
  authenticated:
    redirect_url: ''
    weight: '-10'
  content_editor:
    redirect_url: ''
    weight: '-10'
  administrator:
    redirect_url: ''
    weight: '-10'
  formateur:
    redirect_url: ''
    weight: '-10'
  stagiaire:
    redirect_url: ''
    weight: '-10'
